# Generated by Django 2.1 on 2019-10-10 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('En_Word', models.TextField()),
                ('Bn_Word', models.TextField()),
                ('En_Trans', models.TextField(blank=True, null=True)),
                ('Bn_Trans', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='englishwords',
            name='Level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.Level'),
        ),
    ]
